### ISSUE TITLE
Tutorial 2 Lesson 4 - Case Study: Check-in 1

### ISSUE THREAD

**Issue by juliaparish** [OpenIntroStat/ims-tutorials#134] opened 2021-12-20 20:38 UTC
In Tutorial 2 Lesson 4 - Case Study: Check-in 1 Image and spam interpretation section, the question posed is: 
Which of the following interpretations of the plot is valid?

<img width="1300" alt="Screen Shot 2021-12-19 at 4 03 15 PM" src="https://user-images.githubusercontent.com/88252036/146829465-e0cc3752-ba12-46de-b974-850a43c9e911.png">

Does it seem the "correct" answer may be inaccurate? One of the two "correct" responses states, "Emails with images have a higher proportion that are spam than do emails without images." Upon reviewing the proportion graph above the question, this is NOT a valid interpretation.

**Comment by mamcisaac** [comment] 2022-08-22 15:40
Duplicate of #137

**Closed** 2022-09-04 17:47 UTC
